# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inmate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='house',
            name='code',
        ),
        migrations.AlterField(
            model_name='rasperrypi',
            name='code',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AlterField(
            model_name='terminalrasperrypi',
            name='code',
            field=models.FileField(upload_to=b''),
        ),
        migrations.AddField(
            model_name='inmate',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.House'),
        ),
    ]
