# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-03 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_auto_20160921_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='function',
            name='code',
            field=models.FileField(upload_to='MicroControlerScripts/RassperrypiCodes/Functions'),
        ),
        migrations.AlterField(
            model_name='rasperrypi',
            name='code',
            field=models.FileField(upload_to='MicroControlerScripts/RassperrypiCodes'),
        ),
        migrations.AlterField(
            model_name='terminalrasperrypi',
            name='code',
            field=models.FileField(upload_to='MicroControlerScripts/RassperrypiCodes'),
        ),
    ]
