# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-04 07:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_auto_20161003_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='function',
            name='arduinoboard',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='function',
            name='Trasperrypi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.TerminalRasperrypi'),
        ),
        migrations.AlterField(
            model_name='function',
            name='command',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='function',
            name='rasperrypi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='v1.Rasperrypi'),
        ),
    ]
